### ISSUE TITLE
文档部分

### ISSUE THREAD

**Issue by rowthan** [OYsun/VueCircleMenu#11]
本来想在你基础上做一个定制的，但是下载代码下来看发现有点困难。主要是才开始学webpack所以对你打包部分不是很了解，如果可以的话希望能够相应部分说明文档。
再有一个是个人觉得demo写得不是很好，这个产品应该是具备独立使用的，但是index.html并没有使用到最终打包出来的CircleMenu.js文件啊，所以对于怎么引用你这个文件并不清楚。

**Comment by OYsun** [comment]
你好
- webpack打包请学习相关webpack知识
- 如果想做定制很简单，复制src里面的文件到你得vue工程里修改就可以了
- demo用vue写的，使用vue-cli脚手架，进行了打包处理，所以无法直观看到怎么引用这个组件的
