### ISSUE TITLE
colors不能正常使用

### ISSUE THREAD

**Issue by MaomaoFE** [OYsun/VueCircleMenu#3]
`[Vue warn]: Invalid prop: type check failed for prop "colors". Expected Array, got String. 
(found in component <CirleMenu>)`
添加colors报错

**Comment by MaomaoFE** [comment]
搞定，colors写成 :colors就可以了，另外，文档里面colors数组中有一个少了#

**Comment by OYsun** [comment]
嗯，又粗心了，谢谢指正。
